### PR TITLE
Added customize options.\nRenamed ercn-notify ercn-notify-hook.

### PR DESCRIPTION
**Pull request by PhilHudson**

### CODE REVIEW

**Comment by leathekd** [comment]
Hmm, the change from `ercn-notify` to `ercn-notify-hook`, while totally correct, would break existing installs.  I'm not sure how big of a problem that actually is, though.  

I do like the name change, so I'm thinking something along the lines of:
1. keep the name change
2. bump the version to 2.0.0 (to better indicate a breaking change)
3. at notification time, check for `(boundp 'ercn-notify)` and warn that the name has changed

What do you think?

**Comment by PhilHudson** [comment]
On Mon, 06 Apr 2015 at 10:34:24 pm BST, David Leatherman notifications@github.com wrote:

> Hmm, the change from ercn-notify to ercn-notify-hook, while totally correct,
> would break existing installs. I'm not sure how big of a problem that actually
> is, though. 
> 
> I do like the name change, so I'm thinking something along the lines of:
> 1. keep the name change
> 2. bump the version to 2.0.0 (to better indicate a breaking change)
> 3. at notification time, check for (boundp 'ercn-notify) and warn that the name
> has changed
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHub.

The obsolete-alias declaration prevents breakage while posting a warning
to change to the new term.

## 

Phil Hudson                   http://hudson-it.ddns.net
@UWascalWabbit                 PGP/GnuPG ID: 0x887DCA63

**Comment by leathekd** [comment]
Ah, I totally missed that line.  Nice.

**Comment by leathekd** [comment]
Thanks for the PR!

**Pull request merged**
